#define LIB_FOLDER "./asset_library"
#define MESH_LIB_FOLDER "./asset_library/mesh_library"
#define SHADER_LIB_FOLDER "./resources/shaders"
#define MESH_FILE_NAME "mesh.pkd"
#define MATERIAL_FILE_NAME "def_mats.pkd"